/**
 * Generated by QueryFish — do not edit.
 *
 * Re-run `npx queryfish generate` after changing your OpenAPI document.
 */

import { createMutation } from 'react-query-kit';
import { createPet, updatePet, deletePet } from './requests.js';
import type {
  CreatePetVariables,
  CreatePetResponse,
  UpdatePetVariables,
  UpdatePetResponse,
  DeletePetVariables,
  DeletePetResponse,
} from './types.js';

/**
 * Create a pet
 */
export const useCreatePet = createMutation<CreatePetResponse, CreatePetVariables>({
  mutationFn: createPet,
});

/**
 * Update a pet
 */
export const useUpdatePet = createMutation<UpdatePetResponse, UpdatePetVariables>({
  mutationFn: updatePet,
});

/**
 * Delete a pet
 */
export const useDeletePet = createMutation<DeletePetResponse, DeletePetVariables>({
  mutationFn: deletePet,
});
