/**
 * Generated by QueryFish — do not edit.
 *
 * Re-run `npx queryfish generate` after changing your OpenAPI document.
 */

import { createQuery } from 'react-query-kit';
import { listPets, getPet, listOwnerPets } from './requests.js';
import type {
  ListPetsVariables,
  ListPetsResponse,
  GetPetVariables,
  GetPetResponse,
  ListOwnerPetsVariables,
  ListOwnerPetsResponse,
} from './types.js';

/**
 * List all pets
 */
export const useListPets = createQuery<ListPetsResponse, ListPetsVariables>({
  queryKey: ['pets'],
  fetcher: listPets,
});

/**
 * Get a pet by ID
 */
export const useGetPet = createQuery<GetPetResponse, GetPetVariables>({
  queryKey: ['pets', '{petId}'],
  fetcher: getPet,
});

/**
 * List an owner's pets
 */
export const useListOwnerPets = createQuery<
  ListOwnerPetsResponse,
  ListOwnerPetsVariables
>({
  queryKey: ['owners', '{ownerId}', 'pets'],
  fetcher: listOwnerPets,
});
