/**
 * Generated by QueryFish — do not edit.
 *
 * Re-run `npx queryfish generate` after changing your OpenAPI document.
 */

import { client } from '../client';
import type {
  ListPetsVariables,
  ListPetsResponse,
  CreatePetVariables,
  CreatePetResponse,
  GetPetVariables,
  GetPetResponse,
  UpdatePetVariables,
  UpdatePetResponse,
  DeletePetVariables,
  DeletePetResponse,
  ListOwnerPetsVariables,
  ListOwnerPetsResponse,
} from './types.js';

/**
 * List all pets
 */
export const listPets = (variables: ListPetsVariables) =>
  client.request<ListPetsResponse>({
    method: 'GET',
    url: '/pets',
    params: {
      limit: variables.limit,
      status: variables.status,
    },
  });

/**
 * Create a pet
 */
export const createPet = (variables: CreatePetVariables) =>
  client.request<CreatePetResponse>({
    method: 'POST',
    url: '/pets',
    data: variables.body,
  });

/**
 * Get a pet by ID
 */
export const getPet = (variables: GetPetVariables) =>
  client.request<GetPetResponse>({
    method: 'GET',
    url: `/pets/${variables.petId}`,
  });

/**
 * Update a pet
 */
export const updatePet = (variables: UpdatePetVariables) =>
  client.request<UpdatePetResponse>({
    method: 'PUT',
    url: `/pets/${variables.petId}`,
    data: variables.body,
  });

/**
 * Delete a pet
 */
export const deletePet = (variables: DeletePetVariables) =>
  client.request<DeletePetResponse>({
    method: 'DELETE',
    url: `/pets/${variables.petId}`,
  });

/**
 * List an owner's pets
 */
export const listOwnerPets = (variables: ListOwnerPetsVariables) =>
  client.request<ListOwnerPetsResponse>({
    method: 'GET',
    url: `/owners/${variables.ownerId}/pets`,
  });
