/**
 * Generated by OpenQuery — do not edit.
 *
 * Re-run `npx openquery generate` after changing your OpenAPI document.
 */

export interface Pet {
  /**
   * Unique identifier.
   */
  id: string;
  name: string;
  tag?: string;
  status?: 'available' | 'pending' | 'sold';
  owner?: Owner;
  birthDate?: string;
}

export interface NewPet {
  name: string;
  tag?: string;
}

export interface Owner {
  id: string;
  name?: string;
  email?: string;
}

/**
 * Variables for `GET /pets`.
 */
export type ListPetsVariables = {
  /**
   * Maximum number of pets to return.
   */
  limit?: number;
  status?: 'available' | 'pending' | 'sold';
};

export type ListPetsResponse = Pet[];

/**
 * Variables for `POST /pets`.
 */
export type CreatePetVariables = {
  body: NewPet;
};

export type CreatePetResponse = Pet;

/**
 * Variables for `GET /pets/{petId}`.
 */
export type GetPetVariables = {
  /**
   * The pet's unique identifier.
   */
  petId: string;
};

export type GetPetResponse = Pet;

/**
 * Variables for `PUT /pets/{petId}`.
 */
export type UpdatePetVariables = {
  petId: string;
  body: NewPet;
};

export type UpdatePetResponse = Pet;

/**
 * Variables for `DELETE /pets/{petId}`.
 */
export type DeletePetVariables = {
  petId: string;
};

export type DeletePetResponse = void;

/**
 * Variables for `GET /owners/{ownerId}/pets`.
 */
export type ListOwnerPetsVariables = {
  ownerId: string;
};

export type ListOwnerPetsResponse = Pet[];
