/** Small helpers shared by the emitters. */

export const GENERATED_HEADER = `/**
 * Generated by QueryFish — do not edit.
 *
 * Re-run \`npx queryfish generate\` after changing your OpenAPI document.
 */`

/** Render a JSDoc block, or nothing when there is nothing to say. */
export function jsdoc(
    parts: {
        summary?: string | undefined
        description?: string | undefined
        deprecated?: boolean | undefined
        tags?: string[] | undefined
    },
    indent = '',
): string {
    const lines: string[] = []

    if (parts.summary) lines.push(...parts.summary.split('\n'))
    if (parts.description && parts.description !== parts.summary) {
        if (lines.length > 0) lines.push('')
        lines.push(...parts.description.split('\n'))
    }
    if (parts.deprecated) {
        if (lines.length > 0) lines.push('')
        lines.push('@deprecated')
    }

    if (lines.length === 0) return ''

    const body = lines.map((line) => `${indent} * ${line}`.trimEnd()).join('\n')
    return `${indent}/**\n${body}\n${indent} */\n`
}

/** A JS string literal, preferring single quotes to match common Prettier config. */
export function stringLiteral(value: string): string {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}
